# Generated by Django 5.1.2 on 2024-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('files', models.FileField(upload_to='')),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
