# Generated by Django 5.1.2 on 2024-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
